on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
name: Mirror GitHub Repo to Gitee
jobs:
  run:
    name: Sync-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/openbiox
        dst: gitee/XenaShiny
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org
        white_list: 'UCSCXenaShinyV1'
        force_update: true
